### ISSUE TITLE
Apple Rejects this

### ISSUE THREAD

**Issue by cujo30227** [Handelabra/HSLUpdateChecker#7]
Hi,
Just to warn other users: I had HSLUpdateChecker in my apps since 2 years, but now Apple starts to reject my apps because of the update checker. I appealed to the rejection, but to no avail. Here is their response:

10.6: Apple and our customers place a high value on simple, refined, creative, well thought through interfaces. They take more work but are worth it. Apple sets a high bar. If your user interface is complex or less than very good it may be rejected 

Your app includes an update button or alerts the user to update the app. To avoid user confusion, app version updates must utilize the iOS built-in update mechanism. 

Please remove the update feature from your app. To distribute a new version of your app, upload the new app binary version into the same iTunes Connect record you created for the app’s previous version.

**Comment by MigrantP** [comment]
Good to know. There's probably no need to use HSLUpdateChecker anymore, since most users will have automatic updates turned on.

**Comment by 111vandana** [comment]
There are no any problem with HSLUpdateChecker. I think you add update button manually in your app so you get rejection from Apple store . I used this class in our app and its approved by apple store.
https://itunes.apple.com/app/id895331100

**Comment by stopiccot** [comment]
The problem with this checker is that it incorrectly compares versions. For example I submit new 2.3 version for review, and current version is 2.2. Apple reviewers will get "There is a new 2.2 version" notification all the time and that is probably what pisses them off.

**Comment by MigrantP** [comment]
No, the problem is that "Your app includes an update button or alerts the user to update the app. To avoid user confusion, app version updates must utilize the iOS built-in update mechanism." Just don't use this anymore, it's not necessary.
